# Packages that are not available in the package manager are listed here and installed with the appropriate method.
#
# Attributes:
#   name: The name of the package.
#   repository: The GitHub repository of the package in the format "owner/repo".
#   systems: The operating systems on which the package should be installed. Must match .chezmoi.os.
#   version_regex (optional): A custom regex to extract the version from `binary --version`.
#   required_architecture (optional): The architecture required for the binary. If the current architecture does not match, the binary will not be installed. Must match .chezmoi.arch.
#   install_filter (optional): Filters to use when installing the package. Must match the name of a filter in .chezmoi.data - ie "dev_computer", "personal_computer", "homelab_member".
#   remove_from_release (optional): A regex used to filter out releases. Useful when more than one release is available for your platform.
#   executable_name (optional): Name of executable if different from name of package.

[binaries]
    [binaries.rip2]
        description           = "A safe and ergonomic alternative to rm"
        executable_name       = ""
        install_filter        = ""
        name                  = "rip"
        remove_from_release   = ""
        repository            = "MilesCranmer/rip2"
        required_architecture = ""
        systems               = ["linux"]
        version_regex         = ""

    [binaries.zoxide]
        description           = "A fast, user-friendly alternative to cd"
        executable_name       = ""
        install_filter        = ""
        name                  = "zoxide"
        remove_from_release   = ""
        repository            = "ajeetdsouza/zoxide"
        required_architecture = ""
        systems               = ["linux"]
        version_regex         = ""