[secrets]
    main_ssh_key       = "op://yjnsvyqenba2te2clggojrsbyq/nkf6j5jqpk5v5sb6t3ipf5zdye/Jigar - Main SSH"
    github_ssh_key     = "op://yjnsvyqenba2te2clggojrsbyq/6pzpgnpqpk6ss25cnskbysxcv4/Github Macbook"
    pitch_app_creds    = "op://yjnsvyqenba2te2clggojrsbyq/by7ay4ost3rdf37th6snpfaunq/Pitch Application Credentials"
  